export const SET_FILENAME = 'SET_FILENAME';
export const SET_MENUVISIBLE = 'SET_MENUVISIBLE';
export const SET_SETTINGVISIBLE = 'SET_SETTINGVISIBLE';
export const SET_DEFAULT_FONT_SIZE = 'SET_DEFAULT_FONT_SIZE';
